[tox]
minversion = 4.0
envlist = py{38,39,310,311,312,313}, flake8, coverage
isolated_build = True

[testenv]
deps = -r{toxinidir}/test-requirements.txt
setenv = LANGUAGE=en
allowlist_externals = *
commands =
    /usr/bin/find . -type f -name "*.pyc" -delete
    pytest {posargs}

[testenv:flake8]
basepython = python3
deps = flake8>=7.0.0
commands =
    flake8 --max-line-length=88 maguiclient risuclient

[testenv:ruff]
basepython = python3
deps = ruff>=0.15.0
commands =
    ruff check maguiclient risuclient

[testenv:coverage]
deps = -r{toxinidir}/test-requirements.txt
commands =
    pytest --cov=risuclient --cov=maguiclient --cov-report=html --cov-report=term

[testenv:venv]
commands = {posargs}

[testenv:language_es]
setenv = LANGUAGE=es
commands = pytest {posargs}

[testenv:markdown]
commands = markdownlint .

[testenv:httpd]
commands = python -m http.server 8000
